<h1><?= $url['name'] ?></h1>
<div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap" data-test="url">
        <tbody>
            <tr>
                <td>ID</td>
                <td><?= $url['id'] ?></td>
            </tr>
            <tr>
                <td>Имя</td>
                <td><?= $url['name'] ?></td>
            </tr>
            <tr>
                <td>Дата создания</td>
                <td><?= $url['created_at'] ?></td>
            </tr>
        </tbody>
    </table>
</div>
<h2 class="mt-5 mb-3">Проверки</h2>
<form method="post" action="<?= $routeParser->urlFor('urls.checks', ['url_id' => $url['id']]) ?>">
    <input type="submit" class="btn btn-primary" value="Запустить проверку">
</form>
<table class="table table-bordered table-hover" data-test="checks">
    <thead>
        <tr>
            <th>ID</th>
            <th>Код ответа</th>
            <th>H1</th>
            <th>Title</th>
            <th>Description</th>
            <th>Дата создания</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($checks as $check) : ?>
        <tr>
            <td><?= $check['id'] ?></td>
            <td><?= $check['status_code'] ?? '' ?></td>
            <td><?= $check['h1'] ?? '' ?></td>
            <td><?= $check['title'] ?? '' ?></td>
            <td><?= $check['description'] ?? '' ?></td>
            <td><?= $check['created_at'] ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>