<!DOCTYPE html>
<html lang="ru" xml:lang="ru">
    <head>
        <title>Анализатор страниц</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <?php include $this->templatesPath . '/components/header.phtml'; ?>
        <?php include $this->templatesPath . '/components/flash.phtml'; ?>
        <main class="flex-grow-1">
            <div class="container-lg mt-3">
                <?= $content ?>
            </div>
        </main>
    </body>
</html>