<!DOCTYPE html>
<html lang="ru" xml:lang="ru">
    <head>
        <title>Анализатор страниц</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <header class="flex-shrink-0">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
                <a class="navbar-brand" href="/">Анализатор страниц</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link <?= $currentPage === '/' ? 'active' : '' ?>" href="/">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link <?= $currentPage === '/urls' ? 'active' : '' ?>" href="/urls">Сайты</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <?php if (isset($flash)) : ?>
        <?php if (isset($flash['success'])) : ?>
        <div class="alert alert-success" role="alert"><?= $flash['success'][0] ?></div>
        <?php endif; ?>
        <?php if (isset($flash['failure'])) : ?>
        <div class="alert alert-danger" role="alert"><?= $flash['failure'][0] ?></div>
        <?php endif; ?>
        <?php endif; ?>
        <main class="flex-grow-1">
            <div class="container-lg mt-3">
                <?= $content ?>
            </div>
        </main>
    </body>
</html>