<!DOCTYPE html>
<html>
    <head>
        <title>Анализатор страниц</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <header class="flex-shrink-0">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
                <a class="navbar-brand" href="/">Анализатор страниц</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="/">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/urls">Сайты</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <main class="flex-grow-1">
            <div class="container-lg mt-3">
                <h1></h1>
                <div class="row">
                    <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                        <h1 class="display-3">Анализатор страниц</h1>
                        <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                        <form action="/urls" method="post" class="row" required="">
                            <div class="col-8">
                                <input type="text" name="url[name]" value="<?= htmlspecialchars($url['name'] ?? ''); ?>"
                                class="form-control form-control-lg <?php if (isset($errors)) : ?> is-invalid"<?php endif ?>
                                placeholder="https://www.example.com">
                                <?php if (isset($errors['name'])) : ?>
                                <div class="invalid-feedback d-block"><?= $errors['name'] ?></div>
                                <?php endif ?>
                            </div>
                            <div class="col-2">
                                <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </main>
    </body>
</html>