<!DOCTYPE html>
<html>
    <head>
        <title>Анализатор страниц</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <header class="flex-shrink-0">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
                <a class="navbar-brand" href="/">Анализатор страниц</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="/">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/urls">Сайты</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <?php if (isset($flash['success'])) : ?>
        <div class="alert alert-success" role="alert"><?= $flash['success'][0] ?></div>
        <?php endif; ?>
        <?php if (isset($flash['failure'])) : ?>
        <div class="alert alert-danger" role="alert"><?= $flash['failure'][0] ?></div>
        <?php endif; ?>
        <main class="flex-grow-1">
            <div class="container-lg mt-3">
                <h1><?= $url['name'] ?></h1>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover text-nowrap" data-test="url">
                        <tbody>
                            <tr>
                                <td>ID</td>
                                <td><?= $url['id'] ?></td>
                            </tr>
                            <tr>
                                <td>Имя</td>
                                <td><?= $url['name'] ?></td>
                            </tr>
                            <tr>
                                <td>Дата создания</td>
                                <td><?= $url['created_at'] ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <h2 class="mt-5 mb-3">Проверки</h2>
                <form method="post" action="/urls/<?= $url['id'] ?>/checks">
                    <input type="submit" class="btn btn-primary" value="Запустить проверку">
                </form>
                <table class="table table-bordered table-hover" data-test="checks">
                    <tbody>
                        <tr>
                            <th>ID</th>
                            <th>Код ответа</th>
                            <th>h1</th>
                            <th>title</th>
                            <th>description</th>
                            <th>Дата создания</th>
                        </tr>
                        <?php foreach ($checks as $check) : ?>
                        <tr>
                            <td><?= $check['id'] ?></td>
                            <td><?= $check['status_code'] ?? '' ?></td>
                            <td><?= $check['h1'] ?? '' ?></td>
                            <td><?= $check['title'] ?? '' ?></td>
                            <td><?= $check['description'] ?? '' ?></td>
                            <td><?= $check['created_at'] ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </main>
    </body>
</html>