<?php if (!empty($flash)) : ?>
    <?php if (isset($flash['success'])) : ?>
        <?php foreach ($flash['success'] as $message) : ?>
            <div class="alert alert-success" role="alert"><?= $message ?></div>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if (isset($flash['failure'])) : ?>
        <?php foreach ($flash['failure'] as $message) : ?>
            <div class="alert alert-danger" role="alert"><?= $message ?></div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>