<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="<?= $routeParser->urlFor('home') ?>">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <?php
                    $isActive = ($_SERVER['REQUEST_URI'] ?? '') === $routeParser->urlFor('home');
                    ?>
                    <a class="nav-link <?= $isActive ? 'active' : '' ?>" href="<?= $routeParser->urlFor('home') ?>">Главная</a>
                </li>
                <li class="nav-item">
                    <?php
                    $isActive = ($_SERVER['REQUEST_URI'] ?? '') === $routeParser->urlFor('urls.index');
                    ?>
                    <a class="nav-link <?= $isActive ? 'active' : '' ?>" href="<?= $routeParser->urlFor('urls.index') ?>">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
</header>